[versions]
# Defalut
androidGradlePlugin = "8.1.2"
kotlin = "1.8.10"

# AndroidX
androidXCore = "1.9.0"
androidXLifeCycle = "2.6.1"
androidXAppcompat = "1.6.1"

#Compose
composeUi = "1.3.3"
activityCompose = "1.7.0"
composeMaterial3 = "1.1.2"
composeCompiler = "1.4.3"
composeNav = "2.5.3"

# Test
junit = "4.13.2"
androidXJunit = "1.1.5"
espresso = "3.5.1"
material = "1.10.0"
compose-bom = "2023.03.00"

# Library
orbit = "6.1.0"
hilt = "2.44"
hilt-navigation = "1.0.0"
ktor = "2.3.7"
kotlinxSerializationJson = "1.5.1"
room = "2.5.0"

[libraries]
# kotlinx, kotlin
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

# androidx
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidXCore" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidXLifeCycle" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidXAppcompat" }

# compose
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "composeUi" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "composeUi" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "composeUi" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "composeUi" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "composeUi" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "composeUi" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial3" }
compose-nav = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNav" }

# test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidXJunit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }

# orbit-mvi
orbit-core = { group = "org.orbit-mvi", name = "orbit-core", version.ref = "orbit" }
orbit-viewmodel = { group = "org.orbit-mvi", name = "orbit-viewmodel", version.ref = "orbit" }
orbit-compose = { group = "org.orbit-mvi", name = "orbit-compose", version.ref = "orbit" }

# ktor
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-logging-jvm = { group = "io.ktor", name = "ktor-client-logging-jvm", version.ref = "ktor" }
ktor-client-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }

# hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation" }

# room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

# Define Dependeicies used in build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }


[plugins]
com-android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
com-android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }


[bundles]
compose = ["activity-compose", "compose-ui", "compose-ui-graphics",
    "compose-ui-tooling", "compose-ui-tooling-preview", "compose-ui-test-manifest",
    "compose-ui-test-manifest", "compose-ui-test-junit4", "compose-material3", "compose-nav"]
orbit = ["orbit-core", "orbit-viewmodel", "orbit-compose"]
ktor = ["ktor-client-core", "ktor-client-cio", "ktor-client-logging-jvm", "ktor-client-serialization",
    "ktor-client-content-negotiation"]


